#!/bin/sh

echo Running CardTest...
gst-sunit -f test/testcard.st CardTest
echo Running PlayerTest...
gst-sunit -f test/testplayer.st PlayerTest
echo Running DeckTest...
gst-sunit -f test/testdeck.st DeckTest
